#!/bin/zsh
cd /Users/atlas/astrocade-game6
STYLE="Appetising stylised kitchen things built as chunky, slightly exaggerated toy-like forms with soft rounded edges and generous bevels, in saturated true food and kitchen colours with gentle roughness (glossy where food is wet, satin ceramic, brushed steel), lit like a sunny kitchen; olives are characters with big simple eyes; no text, glyphs, labels or logos anywhere."
BASE="A stylised 3D video game render (not a painting, not a photo), a tower defense game in progress, camera above and behind at about 50 degrees looking along a long kitchen counter that recedes into the distance; the action is centred in the middle of the frame. A winding path of small glossy olives with big cartoon eyes marches in a line along the counter toward a tall club sandwich with a toothpick on a plate in the centre foreground. Beside the path, sandwich-stack towers stand on round coasters: bread slices stacked with lettuce, tomato, cheese and bacon, topped with a toothpick crossbow ballista or a green pickle cannon. Giant kitchen objects tower around the field for scale. Saturated appetising colours, soft light, crisp game-asset look, no text, no UI, no HUD, no logos, no letters."
P1="$BASE Stage: The Cutting Board. Sunny morning: a warm butcher-block wooden counter with a big maple cutting board, beside a bright window with sunbeams, sage green square tiled backsplash, a red enamel toaster, a red kettle, a dark wood knife block, a cream bread bin. $STYLE"
P2="$BASE Stage: The Stovetop. Late morning on a cream enamel stovetop: the olive path winds between four black cast-iron burner grates, one burner glowing with a ring of blue and orange flame, copper frying pans, a red enamel kettle, sage green tiled backsplash behind, warm sunlight from the side. $STYLE"
P3="$BASE Stage: The Sink. Noon: a steel sink drainboard and white marble counter, the olive path crosses a chrome dish-rack bridge over the drainboard grooves, a gleaming steel tap, stacked cream plates and glasses in the dish rack, soap bubbles, a sage green tiled backsplash, bright midday window light. $STYLE"
P4="$BASE Stage: Sunday Lunch. Afternoon on a dining table with a blue-and-white checked tablecloth: the olive path winds between big white dinner plates, giant silver forks and knives, a wicker bread basket, a pepper mill, wine glasses, a vase of flowers, warm afternoon light through a window. $STYLE"
P5="$BASE Stage: Cocktail Hour. Evening on a dark walnut bar cart and side table in warm golden lamp light: the olive path winds between cocktail glasses, a martini glass with an olive on a pick, an ice bucket, a cocktail shaker, brass details, a glowing table lamp, deep warm amber and teal evening tones with pools of warm light, still saturated and readable. $STYLE"
P6="$BASE Boss moment: a giant glass olive jar with a red lid, as tall as the toaster, with big angry cartoon eyes, waddling down the middle of the sunny butcher-block counter toward the sandwich, olives spilling out around it, towers firing toothpicks and pickles at it, dramatic but bright and comic, sage tile backsplash and red toaster behind. $STYLE"
python3 tools/atlas_img.py std ref/concept/01_cutting_board.png concept-01-cutting-board "$P1" > work/art_scratch/c1.log 2>&1 &
python3 tools/atlas_img.py std ref/concept/02_stovetop.png concept-02-stovetop "$P2" > work/art_scratch/c2.log 2>&1 &
python3 tools/atlas_img.py std ref/concept/03_sink.png concept-03-sink "$P3" > work/art_scratch/c3.log 2>&1 &
python3 tools/atlas_img.py std ref/concept/04_sunday_lunch.png concept-04-sunday-lunch "$P4" > work/art_scratch/c4.log 2>&1 &
wait
python3 tools/atlas_img.py std ref/concept/05_cocktail_hour.png concept-05-cocktail-hour "$P5" > work/art_scratch/c5.log 2>&1 &
python3 tools/atlas_img.py std ref/concept/06_boss_jar.png concept-06-boss-jar "$P6" > work/art_scratch/c6.log 2>&1 &
wait
